Create Beyond06-SOW.md for next course with updated dates
redhat-beyond/documents pull request #8
Opened 2021-10-04 13:45 UTC by mgold1234

2021-10-05 06:10 UTC, ifireball requested changes
Overall good work, but it does seem there are more sections that need to be updated.

2021-10-05 06:10 UTC, ifireball commented on Beyond06-SOW.md
> +|                |                        | Incorporate presenting of the 1st exercise and the skill evaluation form in the 1st lecture
The above line is probably not something the student should see - it looks like a task I wrote for myself...

2021-10-05 06:10 UTC, ifireball commented on Beyond06-SOW.md
> +| 1              | 17.10                  | Intro session (housekeeping) ~50 min +Talk about initial challenges and student selection
why does it say 17/0 here? The intro session is on 10/10...

2021-10-05 06:10 UTC, ifireball commented on Beyond06-SOW.md
> +| 2              | 31.10                  | Team collaboration: Git, GitHub, PRs and issues.
We don't have a Git/GitHub lecture this time, did you update this table at all?

2021-10-05 06:10 UTC, ifireball commented on Beyond06-SOW.md
> +| 4              | 07.11                  | Demo 1:  Pre-requirements  fully working env (PRs, vagrant, issues with dependencies) Student 1: vagrant env Student 2: Django Student 3: Home page Student
No need to write the full requirements in this table, they are specified above already

2021-10-05 06:10 UTC, ifireball commented on Beyond06-SOW.md
> +## Grade Process
We already talk about the performance review above. We can probably just drop the res of this section as it does not correctly describe the actual grading process.

2021-10-05 10:17 UTC, mgold1234 reviewed
fix all comments

2021-10-06 05:57 UTC, ifireball requested changes

2021-10-06 05:57 UTC, ifireball commented on Beyond06-SOW.md
> +* group3: Barak, Daniel, Guy & Eran
Missing group 4?

2021-10-06 05:57 UTC, ifireball commented on Beyond06-SOW.md
> +|                |                        | Self learning: Tool introduction challenge
I think mentioning the 1st challenge both here and in the submission data might be confusing - lets either stick to how I wrote it in the spreadsheet (hand-off v.s. submission) or specify only the submission dates.

2021-10-06 05:57 UTC, ifireball commented on Beyond06-SOW.md
> +| 2              | 17.10                  | Python 101
Missing the submission date for the 2nd challenge here.

2021-10-06 05:57 UTC, ifireball commented on Beyond06-SOW.md
> +| 9              | 19.12                  | Demo 3: Testing, Control logic and UI
Lets keep the demo names consistent between here, the list above and the spreadsheet.

Same goes for lecture names

2021-10-07 06:03 UTC, ifireball requested changes

2021-10-07 06:03 UTC, ifireball commented on Beyond06-SOW.md
> +* group3: Barak, Daniel, Guy & Eran
Not seeing the 4th group yet

2021-10-07 06:03 UTC, ifireball commented on Beyond06-SOW.md
> +|                |                        | Self learning: Tool introduction challenge
Not seeing any change in the file about this

2021-10-07 06:03 UTC, ifireball commented on Beyond06-SOW.md
> +| 2              | 17.10                  | Python 101
Still missing...

2021-10-07 06:03 UTC, ifireball commented on Beyond06-SOW.md
> +| 9              | 19.12                  | Demo 3: Testing, Control logic and UI
I meant for the whole list and table, not just this line - in any case, not seeing the change you've mentioned

2021-10-07 06:03 UTC, ifireball commented on Beyond06-SOW.md
> +## Grade Process
Still seeing the section here...

2022-02-12 18:31 UTC, closed without merging